version: '3.8'

services:
  usersdb:
    container_name: usersdb
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    env_file: .env

  blocknotedb:
    container_name: blocknotedb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - blocknotedb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    restart: unless-stopped
    env_file: .env

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: --requirepass ${REDISPASSWD}
    env_file: .env

volumes:
  postgres-data:
  blocknotedb-data:
