name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test_build_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Go test (selected packages)
        run: |
          go test \
            ./internal/blocknote/repository/blocks \
            ./internal/blocknote/repository/notes \
            ./internal/blocknote/repository/tags  \
            ./internal/auth/repository \
            ./internal/auth/jwt \
            ./internal/redis/repository \
            ./internal/blocknote/domain2 \
            ./internal/blocknote/pkg/text \
            ./internal/blocknote/pkg/block/default/textblock \
            ./internal/blocknote/pkg/block/default/codeblock \
            ./internal/blocknote/pkg/block/default/fileblock \
            ./internal/blocknote/pkg/block/default/headerblock \
            ./internal/blocknote/pkg/block/default/imgblock \
            ./internal/blocknote/pkg/block/default/linkblock \
            ./internal/blocknote/pkg/block/default/listblock \
            ./internal/blocknote/pkg/block/default/quoteblock \
            ./test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tags
        id: meta
        run: |
          echo "sha_tag=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "date_tag=$(date -u +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build & Push gateway
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/docker/gateway/dockerfile
          push: true
          tags: |
            zitrax78/breezynotes-gateway:latest
            zitrax78/breezynotes-gateway:${{ steps.meta.outputs.sha_tag }}
            zitrax78/breezynotes-gateway:${{ steps.meta.outputs.date_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push auth
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/docker/auth/dockerfile
          push: true
          tags: |
            zitrax78/breezynotes-auth:latest
            zitrax78/breezynotes-auth:${{ steps.meta.outputs.sha_tag }}
            zitrax78/breezynotes-auth:${{ steps.meta.outputs.date_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push blocknote
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/docker/blocknote/dockerfile
          push: true
          tags: |
            zitrax78/breezynotes-blocknote:latest
            zitrax78/breezynotes-blocknote:${{ steps.meta.outputs.sha_tag }}
            zitrax78/breezynotes-blocknote:${{ steps.meta.outputs.date_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push redis
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/docker/redis/dockerfile
          push: true
          tags: |
            zitrax78/breezynotes-redis:latest
            zitrax78/breezynotes-redis:${{ steps.meta.outputs.sha_tag }}
            zitrax78/breezynotes-redis:${{ steps.meta.outputs.date_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
